#!/usr/bin/env python
# -*- coding: utf-8 -*-
# kate: space-indent on; indent-width 4; replace-tabs on;

""" Micro-HTTP server that runs a command and returns its output as a plaintext response. """

# /etc/systemd/system/prochttp.service:
#
#  [Unit]
#  WantedBy=multi-user.target
#  Description=ProcHTTP
#  After=network.target
#
#  [Service]
#  Environment=PYTHONIOENCODING=utf-8
#  ExecStart=/usr/bin/python /usr/local/bin/prochttp vnstat -d
#  Restart=always
#  User=root
#
#  [Install]
#  WantedBy=multi-user.target


from flask import Flask, Response

import sys
import subprocess

app  = Flask(__name__)

@app.route("/")
def hai():
    proc = subprocess.Popen(
        sys.argv[1:],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT
    )
    out, _ = proc.communicate()
    return Response(out, mimetype="text/plain")


def main():
    app.debug = False
    app.run(host="::", port=8080)


if __name__ == '__main__':
    main()
