FROM arm32v6/alpine:3.5
RUN apk add --no-cache dumb-init python py-flask
COPY ehzpoll-raspberry /bin/ehzpoll
COPY ehzserve.py /bin/
ENTRYPOINT ["dumb-init", "--"]
CMD ["python", "/bin/ehzserve.py"]

# docker run -v /dev/ttyUSBx:/dev/ttyUSB0 ehzpoll
